require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PromoCodesController do

  # This should return the minimal set of attributes required to create a valid
  # PromoCode. As you add validations to PromoCode, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PromoCodesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all promo_codes as @promo_codes" do
      promo_code = PromoCode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:promo_codes).should eq([promo_code])
    end
  end

  describe "GET show" do
    it "assigns the requested promo_code as @promo_code" do
      promo_code = PromoCode.create! valid_attributes
      get :show, {:id => promo_code.to_param}, valid_session
      assigns(:promo_code).should eq(promo_code)
    end
  end

  describe "GET new" do
    it "assigns a new promo_code as @promo_code" do
      get :new, {}, valid_session
      assigns(:promo_code).should be_a_new(PromoCode)
    end
  end

  describe "GET edit" do
    it "assigns the requested promo_code as @promo_code" do
      promo_code = PromoCode.create! valid_attributes
      get :edit, {:id => promo_code.to_param}, valid_session
      assigns(:promo_code).should eq(promo_code)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PromoCode" do
        expect {
          post :create, {:promo_code => valid_attributes}, valid_session
        }.to change(PromoCode, :count).by(1)
      end

      it "assigns a newly created promo_code as @promo_code" do
        post :create, {:promo_code => valid_attributes}, valid_session
        assigns(:promo_code).should be_a(PromoCode)
        assigns(:promo_code).should be_persisted
      end

      it "redirects to the created promo_code" do
        post :create, {:promo_code => valid_attributes}, valid_session
        response.should redirect_to(PromoCode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved promo_code as @promo_code" do
        # Trigger the behavior that occurs when invalid params are submitted
        PromoCode.any_instance.stub(:save).and_return(false)
        post :create, {:promo_code => {}}, valid_session
        assigns(:promo_code).should be_a_new(PromoCode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PromoCode.any_instance.stub(:save).and_return(false)
        post :create, {:promo_code => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested promo_code" do
        promo_code = PromoCode.create! valid_attributes
        # Assuming there are no other promo_codes in the database, this
        # specifies that the PromoCode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PromoCode.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => promo_code.to_param, :promo_code => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested promo_code as @promo_code" do
        promo_code = PromoCode.create! valid_attributes
        put :update, {:id => promo_code.to_param, :promo_code => valid_attributes}, valid_session
        assigns(:promo_code).should eq(promo_code)
      end

      it "redirects to the promo_code" do
        promo_code = PromoCode.create! valid_attributes
        put :update, {:id => promo_code.to_param, :promo_code => valid_attributes}, valid_session
        response.should redirect_to(promo_code)
      end
    end

    describe "with invalid params" do
      it "assigns the promo_code as @promo_code" do
        promo_code = PromoCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PromoCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => promo_code.to_param, :promo_code => {}}, valid_session
        assigns(:promo_code).should eq(promo_code)
      end

      it "re-renders the 'edit' template" do
        promo_code = PromoCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PromoCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => promo_code.to_param, :promo_code => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested promo_code" do
      promo_code = PromoCode.create! valid_attributes
      expect {
        delete :destroy, {:id => promo_code.to_param}, valid_session
      }.to change(PromoCode, :count).by(-1)
    end

    it "redirects to the promo_codes list" do
      promo_code = PromoCode.create! valid_attributes
      delete :destroy, {:id => promo_code.to_param}, valid_session
      response.should redirect_to(promo_codes_url)
    end
  end

end
